import { StyleSheet } from 'react-native';
import {
  horizontalScale,
  moderateScale,
  normalize,
  verticalScale,
} from '../../../utils/orientation';
import { Colors } from '../../../themes/Colors';
import { Fonts } from '../../../themes/Fonts';

export const styles = StyleSheet.create({
  container: {
    height: '100%',
    width: '100%',
    backgroundColor: Colors.white,
  },
  header: {
    height: verticalScale(60),
    width: '100%',
    backgroundColor: Colors.white,
    justifyContent: 'center',
    shadowColor: Colors.whiteGrey,
    shadowOffset: {
      width: horizontalScale(0),
      height: verticalScale(15),
    },
    shadowOpacity: 1,
    elevation: 4,
    shadowRadius: moderateScale(10),
  },
  headerTitle: {
    fontFamily: Fonts.Poppins_Bold,
    fontSize: normalize(22),
    color: Colors.black,
    textAlign: 'center',
  },
  searchTextContainer: {
    borderRadius: moderateScale(10),
    paddingHorizontal: horizontalScale(12),
    paddingVertical: verticalScale(10),
    height: verticalScale(45),
  },
  cardListContainer: {
    paddingTop: verticalScale(16),
    marginHorizontal: horizontalScale(5),
  },
  card: {
    flex: 0.48,
    borderRadius: moderateScale(8),
    marginBottom: verticalScale(16),
    elevation: 2,
    borderWidth: moderateScale(1),
    borderColor: 'rgba(0,0,0,0.1)',
    overflow: 'hidden',
  },
  productImage: {
    resizeMode: 'cover',
    height: verticalScale(180),
    width: '100%',
  },
  cardTitle: {
    fontSize: normalize(13),
    color: Colors.black,
    fontFamily: Fonts.Poppins_Bold,
    marginBottom: verticalScale(4),
  },
  cardDescription: {
    fontSize: normalize(11),
    fontFamily: Fonts.Poppins_SemiBold,
    color: Colors.dark,
  },
  editBtn: {
    marginTop: verticalScale(8),
    backgroundColor: Colors.blue,
    paddingVertical: verticalScale(4),
    paddingHorizontal: horizontalScale(10),
    borderRadius: moderateScale(6),
    alignSelf: 'flex-end',
  },
  editText: {
    color: 'white',
    fontSize: normalize(12),
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  bottomSheet: {
    position: 'absolute',
    bottom: verticalScale(0),
    height: '50%',
    width: '100%',
    backgroundColor: Colors.white,
    borderTopLeftRadius: moderateScale(20),
    borderTopRightRadius: moderateScale(20),
    padding: moderateScale(20),
    elevation: 5,
  },
  sheetText: {
    fontSize: normalize(18),
    textAlign: 'center',
    fontFamily: Fonts.Poppins_SemiBold,
    marginBottom: verticalScale(10),
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'white',
  },
  scrollContainer: {
    justifyContent: 'center',
    paddingBottom: 30,
  },
  v: {
    alignSelf: 'center',
    marginTop: verticalScale(30),
    marginBottom: verticalScale(20),
    borderWidth: moderateScale(2),
    borderRadius: moderateScale(20),
    borderColor: 'lightgrey',
    justifyContent: 'center',
    alignItems: 'center',
    height: verticalScale(100),
    width: horizontalScale(100),
  },
  img: {
    height: verticalScale(100),
    width: horizontalScale(100),
    borderRadius: moderateScale(20),
    resizeMode: 'cover',
  },
  txt: {
    fontSize: normalize(12),
    color: 'grey',
    fontFamily: Fonts.Poppins_Medium,
    textAlign: 'center',
    margin: moderateScale(10),
  },
  add: {
    backgroundColor: '#f0f8ff',
    position: 'absolute',
    right: -10,
    bottom: -10,
    borderRadius: moderateScale(30),
    padding: moderateScale(6),
    shadowColor: 'grey',
    elevation: 4,
    shadowOffset: {
      width: horizontalScale(4),
      height: verticalScale(6),
    },
    shadowOpacity: 0.2,
    shadowRadius: moderateScale(5),
  },
  plus: {
    height: 15,
    width: 15,
  },
  textInputContainer: {
    borderRadius: moderateScale(10),
    paddingHorizontal: horizontalScale(12),
    paddingVertical: verticalScale(10),
    height: verticalScale(45),
    borderWidth: moderateScale(1),
  },
  submitButton: {
    width: '90%',
    alignSelf: 'center',
    backgroundColor: Colors.blue,
    padding: moderateScale(12),
    borderRadius: moderateScale(10),
    marginTop: verticalScale(20),
  },
  submitText: {
    color: Colors.white,
    textAlign: 'center',
    fontSize: normalize(12),
    fontFamily: Fonts.Poppins_Medium,
  },
  deleteOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteModal: {
    backgroundColor: Colors.white,
    borderRadius: 10,
    padding: 20,
    width: '80%',
    alignItems: 'center',
  },
  textAction: {
    fontSize: normalize(18),
    marginBottom: verticalScale(20),
    fontFamily: Fonts.Poppins_SemiBold,
  },
  action: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  yesAction: {
    backgroundColor: Colors.red,
    padding: moderateScale(10),
    borderRadius: moderateScale(5),
    flex: 1,
    marginRight: horizontalScale(10),
    alignItems: 'center',
  },
  yesText: {
    color: Colors.white,
    fontFamily: Fonts.Poppins_Medium,
  },
  noAction: {
    backgroundColor: Colors.grey,
    padding: moderateScale(10),
    borderRadius: moderateScale(5),
    flex: 1,
    marginLeft: horizontalScale(10),
    alignItems: 'center',
  },
  noText: {
    color: Colors.white,
    fontFamily: Fonts.Poppins_Medium,
  },
});
