import {StyleSheet} from 'react-native';
import {Colors} from '../../../themes/Colors';
import {Fonts} from '../../../themes/Fonts';

export const styles = StyleSheet.create({
  container: {
    alignItems: 'center',
    paddingVertical: 30,
    backgroundColor: '#f0f4f8',
  },
  profileImage: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 3,
    borderColor: '#4e8cff',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  profileActiveDot: {
    resizeMode: 'contain',
    position: 'absolute',
    top: 80,
    left: 80,
    tintColor: Colors.green,
    width: 60,
    height: 60,
  },
  name: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
  },
  email: {
    fontSize: 16,
    color: '#6b7280',
    marginBottom: 20,
  },
  infoCard: {
    width: '90%',
    backgroundColor: '#ffffff',
    padding: 20,
    borderRadius: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: {width: 0, height: 2},
    marginTop: 15,
  },
  label: {
    fontSize: 16,
    fontFamily: Fonts.Poppins_SemiBold,
    color: Colors.dark,
    marginTop: 10,
  },
  value: {
    fontSize: 18,
    fontFamily: Fonts.Poppins_Bold,
    color: Colors.black,
    marginTop: 4,
  },
  logoutButton: {
    backgroundColor: '#ef4444',
    width: '90%',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    marginTop: 30,
    justifyContent: 'center',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowOffset: {width: 0, height: 3},
    shadowRadius: 6,
    elevation: 5,
  },
  logoutText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  logoutLogo: {
    resizeMode: 'contain',
    width: 20,
    height: 20,
    marginLeft: 10,
    tintColor: Colors.white,
  },
});
